[workspace]
members = ["foo", "bar"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2021"

[workspace.dependencies]
# clap = { version = "4", features = ["color"] }
clap = { version = "4", default-features = false, features = ["color"] }
